site_name: RKE2 - Rancher's Next Generation Kubernetes Distribution
repo_url: https://github.com/rancher/rke2
strict: false
theme:
  name: material
  palette:
    primary: blue
  font:
    text: 'Work Sans'
  logo: 'assets/logo-stacked-white-rke2.svg'
  favicon: 'assets/favicon-32x32.png'
#google_analytics:
plugins:
  - search
  - markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - index.md
  - Installation:
    - install/quickstart.md
    - install/airgap.md
  - Architecture:
    - architecture/architecture.md
  - Security:
    - security/hardening_guide.md
    - security/cis_self_assessment.md
    - security/fips_support.md
    - security/policies.md
  - backup_restore.md
  - networking.md
  - helm.md
  - advanced.md
